;;; perinf-package-smoke.el --- Test an archive in a fresh package directory -*- lexical-binding: t; -*-
(require 'package)
(setq user-emacs-directory (make-temp-file "perinf-package-user-" t)
      package-user-dir (expand-file-name "elpa" user-emacs-directory)
      package-enable-at-startup nil)
(package-initialize)
(package-install-file (pop command-line-args-left))
(unless (and (commandp 'perinf) (autoloadp (symbol-function 'perinf)))
  (error "Entry command was not autoloaded"))
(unless (autoloadp (symbol-function 'perinf-create-task))
  (error "Public alias lacks autoload"))
(unless (autoloadp (symbol-function 'perinf-home))
  (error "Home alias lacks autoload"))
(call-interactively 'perinf)
(unless (and (eq perinf-interface-language 'da)
             (string-match-p "Personligt arbejds- og informationssystem" (buffer-name))
             (string-prefix-p "Personligt arbejds- og informationssystem" (buffer-string)))
  (error "Danish package UI failed"))
(princ (format "PACKAGE-INSTALL-AND-AUTOLOAD-OK %s\n" (locate-library "perinf")))
(kill-buffer (current-buffer))
(delete-directory user-emacs-directory t)
