;;; perinf-package-smoke.el --- Test an archive in a fresh package directory -*- lexical-binding: t; -*-
(require 'package)
(let ((argument (pop command-line-args-left)))
  (if (equal argument "--installed")
      (progn
        (setq user-emacs-directory (pop command-line-args-left)
              package-user-dir (expand-file-name "elpa" user-emacs-directory))
        (package-initialize))
    (setq user-emacs-directory (make-temp-file "perinf-package-user-" t)
          package-user-dir (expand-file-name "elpa" user-emacs-directory)
          package-enable-at-startup nil)
    (package-initialize)
    (package-install-file argument)
    ;; Compilation loads dependencies; check activation in a fresh process.
    (let ((status (call-process
                   (expand-file-name invocation-name invocation-directory)
                   nil t nil "-Q" "--batch" "-l" load-file-name
                   "--installed" user-emacs-directory)))
      (delete-directory user-emacs-directory t)
      (unless (zerop status) (error "Fresh-process package check failed: %s" status))
      (princ "FRESH-PACKAGE-INSTALL-AND-AUTOLOAD-OK\n")
      (kill-emacs status))))
(unless (and (commandp 'perinf) (autoloadp (symbol-function 'perinf)))
  (error "Entry command was not autoloaded"))
(unless (autoloadp (symbol-function 'perinf-create-task))
  (error "Public alias lacks autoload"))
(unless (autoloadp (symbol-function 'perinf-home))
  (error "Home alias lacks autoload"))
(unless (and (autoloadp (symbol-function 'perinf-task-activity-mode))
             (not (featurep 'perinf-task)))
  (error "Activity mode autoload eagerly loaded the package"))
(call-interactively 'perinf)
(when (or perinf-task-activity-mode perinf-task-inactivity-check-timer)
  (error "Opening PerInf enabled activity tracking"))
(perinf-task-activity-mode 1)
(unless (timerp perinf-task-inactivity-check-timer)
  (error "Autoloaded activity mode did not start its timer"))
(perinf-task-activity-mode -1)
(unless (and (eq perinf-interface-language 'da)
             (string-match-p "Personligt arbejds- og informationssystem" (buffer-name))
             (string-prefix-p "Personligt arbejds- og informationssystem" (buffer-string)))
  (error "Danish package UI failed"))
(princ (format "PACKAGE-INSTALL-AND-AUTOLOAD-OK %s\n" (locate-library "perinf")))
(kill-buffer (current-buffer))
(delete-directory user-emacs-directory t)
